### ISSUE TITLE
Unable to find explicit activity class 

### ISSUE THREAD

**Issue by ahmadarslan13** [jclehner/rxdroid#11]
Unable to find explicit activity class {at.jclehner.rxdroid/at.jclehner.rxdroid.DoseTimePreferenceActivity2}; have you declared this activity in your AndroidManifest.xml?

**Comment by ahmadarslan13** [comment]
? Can anyone reply me on this?

**Comment by jclehner** [comment]
Removing `applicationIdSuffix '.debug'` in build.gradle should fix this temporarily in debug builds.
