### ISSUE TITLE
RTL Preparation

### ISSUE THREAD

**Issue by yarons** [jclehner/rxdroid#14]
RTL - Right to Left as opposed to LTR (Left to Right) the directionality of text in Latin languages for example.
RTL directionality applies to Hebrew, Arabic, Persian, Urdu, Dhivehi, N'ko, some type of Punjabi and some other less common scripts.

Following my Hebrew translation I'd like to point out some glitches that might occur due to the automatic RTL conversion by Android.

The fraction function might get reversed so it needs to be restratained so that the user will type the numbers in their native order instead of reversed (It's very funny when it happens with time, there are apps which shows times as 53:12 due to this bug).

I will probably need to take a look at the working version in order to detect more bugs such as this one.

Thanks!

**Comment by jclehner** [comment]
Hi Yaron,

the latest source uses your Hebrew translation (thanks!), plus it includes some changes to deal with RTL layouts. One question: when writing a mixed fraction in Hebrew, such as  `1¾`, would this be `1¾` or `¾1`? In your translation, both versions can be found:

```
<string name="_help_msg_to_mixed_mode">אם המינונים הניטלים הם ‎1¾‎ למשל, יש ללחוץ על הכפתור הזה.</string>

<string name="_help_msg_input_mixed">"כדי לציין ערכים כגון 1¾, יש להקליד „1” בשדה השמאלי, „3” בשדה האמצעי ו־„4” בשדה הימני."</string>
```
```

**Comment by yarons** [comment]
Wow, good catch, these are actually wrapped with LRM characters so the logical order (due to the Hebrew directionality) is actualy the number one and then the fraction, with LRM the text is enforced to go the other way around so the first string you mentioned was correct and for the second one (since there was so much to take care of in this string) I actually missed it.

Numbers should go from left to right always, even with Indo-Arabic numbers.

EDIT: I've added a new suggestion and removed the former one, thanks!

**Comment by jclehner** [comment]
Hi Yaron,

please try this version, built from the latest sources, and report the remaining issues.

[RxDroid-0.9.33-rc.zip](https://github.com/jclehner/rxdroid/files/3194486/RxDroid-0.9.33-rc.zip)

**Comment by yarons** [comment]
We have somewhat interesting isses but less critical than I imagined.

First - I select 1 and 2/5, worked with the English version:
![2019-05-19 00 01 08](https://user-images.githubusercontent.com/406826/57974916-d70ec400-79c8-11e9-8653-afa5c1770da1.jpg)

Second - The arrow is reversed:
![2019-05-19 00 00 31](https://user-images.githubusercontent.com/406826/57974917-d70ec400-79c8-11e9-98b2-00a0f2b0c238.jpg)

Third - Mixed fraction is reversed :) (Sounds familiar):
![2019-05-19 00 01 14](https://user-images.githubusercontent.com/406826/57974918-d70ec400-79c8-11e9-8c99-5ac18b92e8be.jpg)

Thank you!

**Comment by jclehner** [comment]
One question: in the dose log, if a dose was taken at 08:00, but one day late, this is indicated as `08:00 +1`. In your opinion, how should this be handled in RTL languages?

**Comment by yarons** [comment]
Same, spaces between numbers should remain the same, the only thing that matters is to keep this text in LTR mode so the space will not change their positions.

**Comment by jclehner** [comment]
Please try this version, built from 539ff871.

[RxDroid-0.9.33-rc2.zip](https://github.com/jclehner/rxdroid/files/3198825/RxDroid-0.9.33-rc2.zip)

**Comment by jclehner** [comment]
Any more suggestions before this goes live?

**Comment by yarons** [comment]
I'm terribly sorry, I previously used my wife's phone and compared it with the English version on my phone, I'll try again this evening.

**Comment by yarons** [comment]
It's great, continue please :)

**Comment by yarons** [comment]
Is everything fixed?

**Comment by jclehner** [comment]
To my knowledge, yes, all the issues pointed out above have been fixed last year. Are there any other issues with the Hebrew translation that you know of?

**Comment by yarons** [comment]
I think we're good, I'll open another issue if I'll run into something, thank you :)
