### ISSUE TITLE
Add Privacy Policy.

### ISSUE THREAD

**Issue by HarryHeights** [jclehner/rxdroid#16]
Hi, do you have a privacy policy statement? If you don't, I could help create one for you.

**Comment by jclehner** [comment]
RxDroid doesn't use any networking features, so why would it need a privacy policy?

**Comment by jbaber** [comment]
I don't think all users understand that. One that says "this app shares no data because it collects none" is valuable.

**Comment by hydrian** [comment]
I agree with @jbaber. While this is obvious to computer technical people, this would not necessarily be obvious to a non-technical person.

**Comment by jclehner** [comment]
Fixed in 68cafbf084548cdeb391172e2886db68b27e26a9.
