### ISSUE TITLE
Addition of password option, health logbook to Rxdroid

### ISSUE THREAD

**Issue by zoneboy** [jclehner/rxdroid#17]
# Introduction
Rxdroid is an android application that reminds users of taking their medication. It notifies them when to take their pills and also when their pills is about to finish.

# Components

My suggestion is on the 

* Landing page, 
* Add interface, and 
* Preferences interface. 

# Proposal 

> Rxdroid is an important application that tracks medication usage and gives alert on when to refill. It's a great application and can still be improved.

* **Password-** Rxdroid is free to access for anyone. It can be accessed by anyone that is in control of the owner's phone. Patients medical records are private and not divulged to the general public. Why not Rxdroid user-data? I propose the addition of a password option that will pop up before users open the application.

* **Pharmacy and price option-** The add interface possess some cool options such as the drug name, drug schedule, the refill size, and the drug icon. I propose the addition of the pharmacy and price option. Users should be able to input the pharmacy they got the drugs from and the price they got it. This is one important feature for over-the-counter drugs purchase.

* **Health logbook -**The application is a medication tracker and also helps track refills. A great feature to add to it will be tracking the health progress of the user. The logbook will contain a way to input **symptom check**, **measurements**. The **symptom check** will allow users to input the changes to their body system daily. 
The **measurements sub-feature** will include daily check of popular measurements such as weight, blood pressure, and blood sugar. 

# Mockups/Examples

![Comb27052019131720.jpg](https://cdn.steemitimages.com/DQmaNoN8kd2unJZd4syS6V5Te6Hy4hw4QE4CSxRdcj5ecXm/Comb27052019131720.jpg)

You can see how the password feature will look when implemented.

![Comb27052019131649.jpg](https://cdn.steemitimages.com/DQmSYDMTu7BeLRr9gCy9Q1PxWwzKjMLm9SxpqHi3nsWLbLy/Comb27052019131649.jpg)

This is the pharmacy and price option. Users will be able to input the pharmacy they got their drugs from and the price they bought it

![Comb27052019132531.jpg](https://cdn.steemitimages.com/DQmfGpXCHuiD6dxv7mjkE6Y5qZcFxtBRevmvKPfxGVNKAVd/Comb27052019132531.jpg)

This last image is the Health Logbook. The health logbook will lead to the measurement and the symptom check features. You can see a sample of what is in the measurements.

# Benefits 

**Password-** This is an important feature that will greatly improve the application. Medical records of a user should be kept private and as such, Rxdroid should keep the drugs information private. Anybody opening the application can easily get the user medical problems from the drugs taking. This should not be so. The password feature will give the privacy required. 

**Pharmacy and price option-** This is one feature that will be of great benefit especially for users that buy drugs over-the-counter. It will help them remember the pharmacy they got the drugs from and the price they paid for it. It is useful when they want to refill because they can just go to the pharmacy and refill it thereby reducing the stress and time used in trying to get the drugs in another pharmacy to no avail.

**Health logbook-** The essence of drugs is to get well. Keeping track of your medications and keeping track of your health progress should go hand in hand. That is the advantage of this feature. Users can enter their daily improvements in the logbook.

The symptom check will let users keep track of how the symptoms are persisting or reducing. E.g. From heavy headache to slight headache and so on.

The measurements option will allow users to keep track of some popular health checks such as blood pressure, blood sugar, weight and so on. For example, a user with diabetes who is placed on insulin will just been putting the blood sugar level on a daily basis which will help track his progress.

# Conclusion 

These are important features that will improve Rxdroid when implemented. It will make the application more rounded one with those features. This will increase the number of users utilizing it on daily basis.

**Comment by jclehner** [comment]
Unfortunately, development on RxDroid is currently limited to bug fixes, and has been for the past few years. If I had the time and motivation I'd rewrite the application completely, but that's not likely to happen. Regarding your suggestions:

> Password

I've [considered this in the past](https://github.com/jclehner/rxdroid/blob/stable/src/main/java/at/jclehner/rxdroid/LockscreenActivity.java), but never really enabled it. The feature *might* be added in future versions (using a dedicated library though).

> Pharmacy and price option

There's a `comment` field for each drug that is currently not exposed in the UI. This could be used to store arbitrary information, such as pharmacy and price.

> Health logbook

See the first sentence.
