### ISSUE TITLE
ENHANCING RxDRIOD  WITH  THE ADDITION OF  CUSTOM DRUG PHOTOS, MULTI-PERSON SUPPORT, AND MEDICAL  PROGRESS REPORT.

### ISSUE THREAD

**Issue by adewararilwan** [jclehner/rxdroid#18]
## Repository:
https://github.com/jclehner/rxdroid
##### What is RxDroid?<div class="pull-right">![Droid.jpg](https://cdn.steemitimages.com/DQmVYNTfonDJuaFB3jKDSK6pLjv92gF71Cu3a7gLVQAt1Mh/Droid.jpg)</div> 
Rxdroid is an open source android application that functions as a medication reminder and keeps track of users take his/her medication, pill count and issue warning about getting a refill on time.

### Component
My suggestion is on the:
- Preference Interface 
-  Landscape Interface

## PROPOSAL
>  RxDroid application is a medication reminder and it is used to keep track of how and when the user takes medication.

Adding the proposed new features will improve the application
- Custom Drug Photos
- Multi-person Support
- Medical Progress report

#### Custom Drugs Photos-
 I suggest the addition of customs drug photos that will allow the users to take photos of their drugs in order to identify them easily for the user to be sure of taking the right drugs.

#### Multi-person support- 
Assigning specific medication to different people sort by medication, person, and time of the next dose is very present on the RxDroid application. I suggest the addition of multi-person support that will allow the user whole family/relative medications schedule to be organized by the user.

#### Medical Progress report –
I suggest the addition of a medical progress report that will allow the user to have a clear view of their medication report at the end of the month.

# <center>MOCKUP EXAMPLES</center>
![Ibru](https://user-images.githubusercontent.com/48644964/58766715-a8245080-8579-11e9-8104-a7615054d79e.jpg)

The image above shows how the Custom DrugsPhotos feature will look like when implemented that will allow users to take photos of their drug for a clear identification to avoid mix up during medication.

![MultiPerson.jpg](https://cdn.steemitimages.com/DQmRAqetCrebSD7i4zyvqiJnSjYoHWzV8yX5qhVtkcW7XXb/MultiPerson.jpg)
The image above shows how the Multi-Person feature will look like when implemented that will allow users to take note and organized a schedule of his family/relative medication

![Preference.jpg](https://cdn.steemitimages.com/DQmcEFHLHpysjMizqLXcrKo2Adn9rJ2U1x45eQPN45duCKv/Preference.jpg)
 The image above shows how the Medical Progress Report feature will look like when implemented that will allow users able to view the record of medication taken throughout the month 
#### *Custom Drugs Photos*- 
this will be a very important feature that will improve the application. It will allow users to take a clear photo of their drugs that makes the user have a clear identification of drugs and take the right drugs in order to avoid a mix up during medication.

#### *Multi-person support -* 
This will be a very important feature and it will greatly improve the application.   Adding multi-person support to the application will allow the user to take note and organized a schedule of his family/relative medication such as people,  the time and their dose, dose to be taken, etc. It is not only useful for the user alone but along with his/her family/relations etc.

#### *Medical Progress Report:* 
 This also will be important and at the same time improved the application at the end of each month; the user will be able to view the record of medication taken throughout the month in order to have a rightful guess about their health status or achievement.

## Conclusion
This feature when implemented will really improve the application and will only make the application more efficient and reliable and lastly will also increase the user base.

#  My Github Profile
https://github.com/adewararilwan

**Comment by jclehner** [comment]
As already mentioned in #17, new features are unlikely to be added to RxDroid, as development is currently limited to fixing bugs and minor improvements, sorry.
