### ISSUE TITLE
More freedom to set times

### ISSUE THREAD

**Issue by alanruttenberg** [jclehner/rxdroid#22]
Perhaps I'm missing how to do this. I have a somewhat shifted schedule, so want night to start at 10 or 11. However, it seems I can only start night as late as 9pm. The suggestion would be to only constrain times so that they don't overlap. 

Thanks so much for RxDroid! It's been a real help, and it's great to have an app for this that respects privacy (installed using F-Droid).

**Comment by jclehner** [comment]
> The suggestion would be to only constrain times so that they don't overlap.

That's exactly the way it *should* work. I'm guessing that "Night" currently ends at 9pm, so you can't change it to start later than that.

Try the following: click "Night", and when prompted to change the start time just click "Next". Now change the end of "Night" (times past midnight are possible), then click "Back", and set the start time to 11pm!

**Comment by alanruttenberg** [comment]
Maybe I've hit a corner case? I'm attaching screenshots of the times screen and what I see when I tap "Night". As you can see, the "next" button isn't active. If I tap "evening" I do see the "next" button as active. I'm not sure how I got the 9:00 to 9:01 setting - it's been a while since I first set it up. 

![Times screen](https://user-images.githubusercontent.com/241934/87175018-0c016880-c2a6-11ea-9d4c-fc6d53188b95.png)

![Night time settings](https://user-images.githubusercontent.com/241934/87175013-0ad03b80-c2a6-11ea-8659-831bbb800207.png)

**Comment by alanruttenberg** [comment]
Ok, I think I've got it. I first changed the start time to be earlier, then set the end time to midnight, then set the start time to 11pm. So it looks like maybe an off-by-one? Speculating the comparison between start and end time resulted in it thinking they were the same?

**Comment by alanruttenberg** [comment]
Last question: If I set an end time to be 2AM, will it understand it is the 2AM after 11pm, or will it get confused and think it's on the same day?

**Comment by jclehner** [comment]
Yeah, just noticed that I can reproduce this on my device - most likely something like a `<` instead of `<=` comparison. Will fix this soon!

> If I set an end time to be 2AM, will it understand it is the 2AM after 11pm, or will it get confused and think it's on the same day?

For the end time of "Night", times past midnight are interpreted as being on the next day! So something like 11pm-2am will work as expected.
