### ISSUE TITLE
Add option to disable vibration (but keep sound etc)

### ISSUE THREAD

**Issue by jackrgm** [jclehner/rxdroid#25]
The hard vibration used by the app on my OnePlus 3 can be obnoxious at times, especially when dealing with multiple meds (e.g. marking one med dose as taken repeats the reminder for remaining doses).

There doesn't seem to be an option, neither in-app or OS, that allows disabling vibration without disabling the sound and keeping the notification as normal priority.

Adding this option will allow the app to offer a nice middle ground between a noticeable notification without being too disruptive.

**Comment by jclehner** [comment]
Notification modalities on Android have been moved from in-app options to the OS for some time now. Clicking "Customizations" in the in-app settings redirects you to the OS notfication options. From here, you can either select "Alerting" (i.e. sound + vibration), or "Silent". But there's also an "Advanced" option where you can enable/disable vibration separately.
