### ISSUE TITLE
Notifications not working properly on Samsung A51

### ISSUE THREAD

**Issue by borisb74** [jclehner/rxdroid#30]
On my Samsung A51 notifications are not always shown properly. RxDroid is properly listed in the power savings settings as apps which should not be put into standby. 

Android version: 10

**Comment by jclehner** [comment]
Are they not being displayed at all, or too late? Any identifiable pattern?

**Comment by borisb74** [comment]
There is no real pattern behind. Sometimes they are showing, but seldomly. Adaptive power management is also disabled.

**Comment by jclehner** [comment]
There might be more to it than just disabling adaptive power management. See [this website](https://dontkillmyapp.com/samsung) for details.
