### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by trmendes** [jclehner/rxdroid#32]
I see you're just working on fixing bugs, but I'd like to record some of the things/ideas to maybe, implement on rxdroid.

* Description

> A complete description of the drug. To be used to write down the company name and information about it

* Quick description

> To help the user remember what that pill is for. A quick description like "In case of headache", "Joint pain", "Fever"; "Supplement"

* Expiration date

> Some pills like those for headaches are only taken when you have a problem and it would be nice to have an alarm warning when those are about to expire or if they have expired.

* Photos

> To have a picture of the drub box so it is easier to buy it when you go to the pharmacy

* Auto-Backup

> An auto-backup feature to save the user database everyday

**Comment by ghost** [comment]
I would like to suggest a feature for automatically calculating by the time you need more medication what to order (so as to minimize the number of trips to the pharmacy while keeping a low enough stock that minimizes costs - storage, obsoletion and expiration-wise). Example - 1 box of medication A, 1 box of medication B and 2 boxes of medication C.

**Comment by PedanticNuthead** [comment]
Love the app! But a big requirement for me and for many others is a time slot for 'Early Morning'. 
As many meds are needed to be taken on an empty stomach. The 'Morning' slot isnt optimal as it is reserved for the meds after breakfast. My current workaround is putting both the early morning and the morning meds in 1 time slot. Which gets me confused quite often.

Do consider adding that in. As that would be very useful to all senior users of the app.

**Comment by jclehner** [comment]
Thank you for your feature request. However, development on RxDroid has stopped, and is currently limited to fixing serious bugs. Sorry.
