### ISSUE TITLE
Edit / delete taken doses

### ISSUE THREAD

**Issue by craigw84** [jclehner/rxdroid#35]
If I mark a dose as taken, is there any way to edit that later?
eg I might accidentally mark one that I haven't taken yet, so want to undo that / delete it from the history.

Also any way to edit the taken time? eg if I actually took it an hour ago, but didn't mark it as the time. Can I mark it now, but set the correct time in the history?

**Comment by schmave** [comment]
You can delete a taken dose by long tapping on the dose. I don't see any way to edit the taken time though.
