### ISSUE TITLE
Do not play notification sound if DND is on

### ISSUE THREAD

**Issue by k3a** [jclehner/rxdroid#39]
For some reason the notification sound is played even if I have Do Not Disturb enabled (manually or via Bedtime mode).

Maybe it is a feature but I am not sure it is ok for everyone. I need to take a medication early in the day but I don't want rxdroid to wake me up. This makes me set the time later in the day but then it is often a bit too late.

**Comment by webracer999** [comment]
I have a similar problem. In DND mode there is no sound but RxDroid still vibrates. This is different behavior from other applications.
I also had to completely disable vibration for RxDroid notifications  because I get woken up too.

**Comment by lightnin** [comment]
Thanks for making and sharing this helpful software. :)

In DnD mode I hear the same notification sound as when not in DnD mode. Note that in notification settings, the "allow notifications when Do not disturb is on" setting is disabled.
