### ISSUE TITLE
how to restore backups from another phone?

### ISSUE THREAD

**Issue by formula-spectre** [jclehner/rxdroid#40]
I have the backup.rxdbak file, but where do I put it to be restored?

**Comment by formula-spectre** [comment]
`external storage is mounted read only: cannot create backup` I also get this errror; i'm puzzled by this

**Comment by jclehner** [comment]
> I have the backup.rxdbak file, but where do I put it to be restored?

Your "Downloads" folder for example. Then you'll have to open it with RxDroid, from your file browser.

> "external storage is mounted read only: cannot create backup" I also get this errror; i'm puzzled by this

Yes this is a bug, but I don't see it getting fixed anytime soon, as development on RxDroid has pretty much
stopped, aside from fixing crippling bugs, and updating the app to meet Google's Play Store requirements.
