### ISSUE TITLE
Notifications not showing on smartwatch

### ISSUE THREAD

**Issue by Paoleddu** [jclehner/rxdroid#41]
Hello,

As the title says, unfortunately the app's notifications don't show up at all on the watch.
I have manually enabled the setting to allow for the app's notifications to be shown on the watch but unfortunately it doesn't seem to work.

If there's something I can do to help reproduce the issue or do some testing, please let me know.

Hardware & software:
- phone: S22, Android 13
- smartwatch: Galaxy Watch 4, WearOS 3.5

**Comment by jclehner** [comment]
This should be fixed in the latest version.
