### ISSUE TITLE
Features i would like to see

### ISSUE THREAD

**Issue by katastrophe92** [jclehner/rxdroid#42]
Features i would like to have. 
1. Add your meds: name, doses, remaining doses 
2. Make a reminder/ notification and add: the time when you need to take your meds, how many times per day, week, etc
3. Mark the meds you want in this reminder 

For me the most important thing is to not forget to take my meds, also to know how many pills i have left, notify me when I need to order more 

I take 6 different pills at once thats why I would like to combine multiple meds in one reminder and also to keep count of how many do I still have in Stock. Love the app and thanks to the devs

**Comment by jclehner** [comment]
Thank you for your feature request. However, development on RxDroid has stopped, and is currently limited to fixing serious bugs. Sorry.
