### ISSUE TITLE
Loading/saving of DB backups don't work due to missing permission

### ISSUE THREAD

**Issue by ceskyDJ** [jclehner/rxdroid#45]
Hi, I hope it's critical enough bug for fixing, because I need to load backed up DB. When I try to open screen for managing backups (Three dots menu --> "Preferences" --> "Database" --> "Backup/Restore"), it just displays an error "External storage is not readable. Cannot create or restore backups." (see the first screenshot). It didn't wanted to assign a permission for storage and there is no storage permission to allow in system settings (see the second screenshot).

**SW/HW details:**

- Device: Samsung Galaxy S22
- OS: Android 13
- App version: 0.9.35 (freshly installed)

![Screenshot_20230815_151722_RxDroid](https://github.com/jclehner/rxdroid/assets/48548230/1df2d146-e8df-41bd-ad26-569db6dba655)
![Screenshot_20230815_152418_Permission controller](https://github.com/jclehner/rxdroid/assets/48548230/b6856f7b-daf1-4cc6-b832-bcbefef68636)

**Comment by ceskyDJ** [comment]
I'm sorry for a little more emotional issue description. The error made me angry, so my mood was reflected into my text.

**Comment by jclehner** [comment]
Fixed in 0.9.36.
