### ISSUE TITLE
Dose taken time not visible since 0.9.35

### ISSUE THREAD

**Issue by yan12125** [jclehner/rxdroid#48]
For both 0.9.35 and 0.9.37, dose taken time is not visible:
![Screenshot_20231115-221724](https://github.com/jclehner/rxdroid/assets/1937689/8f5bcf94-9b77-4ce8-b0a4-5693c1b9456f)
For 0.9.34.2, the time is displayed as expected:
![Screenshot_20231115-222144](https://github.com/jclehner/rxdroid/assets/1937689/c4cde854-bb73-4694-b769-6318cfbfd7f2)

Those screenshots are from F-Droid packages. I also got the issue with 0.9.37 from Google Play. Could you check if something goes wrong?

**Comment by azizLIGHT** [comment]
0.9.37 has this issue for me too
0.9.34.2 does not have this issue. Downgraded for now

**Comment by schmave** [comment]
Thanks for the quick fix!
