### ISSUE TITLE
Wrong date on reactivate

### ISSUE THREAD

**Issue by EarMaster** [jclehner/rxdroid#5]
I usually use the notification to check my medication. Sometimes when I take my meds a few minutes before the notification pops up I reopen the app (after not having it in foreground for a few days) the date and data displayed are not correct: The app shows the current date, but the displayed data are older (I suspect it shows the data of the last day the app was in foreground). I can even go to the next day and all meds are already checked as taken. I usually double tap the date button to reset the displayed dates and data.

I hope my description was clear enough to find the problem. If not I will try to provide further information.

**Comment by jclehner** [comment]
Thanks, I am aware of the problem, but I haven't had the time to fix it yet. Hopefully in the next release!

**Comment by jclehner** [comment]
This should have been fixed a while ago.
