### ISSUE TITLE
Feature request - temporarily suspend drugs.

### ISSUE THREAD

**Issue by hellomiakoda** [jclehner/rxdroid#51]
I'd like to be able to pause drugs. 
A med I'm on is sometimes not available in my usual cspsule size, and thus I sometimes get 10Mg and told to take two, instead of my usual 20Mg of which I take 1.

It would be helpful to put both in RxDroid and just suspend the one I'm not currently taking without having to delete and later re-add it, and be able to keep the current supply count and previous journal of taken vs missed dose (days while suspended just not being listed in the journal for that medication)

It'd also be helpful to be able to leave meds in there that are temporary, but frequently hlget perscribed - like antibiotics for recurring conditions. Just leave them dormant till I'm on them again.

Both have the added benefit of having a list of my meds that include perscriptions that aren't active.

**Comment by jclehner** [comment]
This feature is already available. When editing a drug, scroll down and you'll find an option named 'Active':

<img src="https://github.com/user-attachments/assets/9a4d6763-ff84-40b9-840b-d3ef18a6f1e0" width="512" />
