### ISSUE TITLE
Timed Doses

### ISSUE THREAD

**Issue by witeshadow** [jclehner/rxdroid#7]
I have a med that needs to be taken every 8 hours. I would like to see a way to track those in RxDroid.

**Comment by jclehner** [comment]
As you may have noticed, the pace of development of RxDroid has slowed down quite a bit. This feature has been on my todo list for quite a while, but I don't know when I'll get around to implementing this - at the moment I'm trying my best to fix existing bugs.

**Comment by witeshadow** [comment]
I really love this project. I've not done android Dev before but I am a CS minor. Can you give guidance on getting this project setup on my home machine? I have Windows and Linux machines.
